
set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86)
set(CMAKE_C_COMPILER clang-cl)
set(CMAKE_CXX_COMPILER clang-cl)
set(CMAKE_LINKER lld-link)
find_program(CMAKE_AR NAMES llvm-lib llvm-lib-21 REQUIRED)
find_program(CMAKE_MT NAMES llvm-mt llvm-mt-21 REQUIRED)
find_program(CMAKE_RC_COMPILER NAMES llvm-rc llvm-rc-21 REQUIRED)
set(CMAKE_C_COMPILER_TARGET i686-pc-windows-msvc)
set(CMAKE_CXX_COMPILER_TARGET i686-pc-windows-msvc)
if("${CIV_MSVC_SDK}" STREQUAL "" AND NOT "${CIV_DEPS}" STREQUAL "")
  set(CIV_MSVC_SDK "${CIV_DEPS}/msvc-sdk")
elseif("${CIV_MSVC_SDK}" STREQUAL "")
  get_filename_component(CIV_MSVC_SDK "${CMAKE_CURRENT_LIST_DIR}/../deps/msvc-sdk" ABSOLUTE)
endif()
set(_civ_libs "/libpath:\"${CIV_MSVC_SDK}/crt/lib/x86\" /libpath:\"${CIV_MSVC_SDK}/sdk/lib/um/x86\" /libpath:\"${CIV_MSVC_SDK}/sdk/lib/ucrt/x86\"")
set(_civ_includes "/imsvc \"${CIV_MSVC_SDK}/crt/include\" /imsvc \"${CIV_MSVC_SDK}/sdk/include/ucrt\" /imsvc \"${CIV_MSVC_SDK}/sdk/include/um\" /imsvc \"${CIV_MSVC_SDK}/sdk/include/shared\"")
set(CMAKE_C_FLAGS_INIT "${_civ_includes}")
set(CMAKE_CXX_FLAGS_INIT "${_civ_includes}")
set(CMAKE_EXE_LINKER_FLAGS_INIT "/machine:x86 ${_civ_libs}")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "/machine:x86 ${_civ_libs}")
set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreadedDLL" CACHE STRING "" FORCE)

